name: Build iOS Tweak

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        
    - name: Build Tweak
      run: |
        make package FINALPACKAGE=1
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AutoClicker_Deb
        path: packages/*.deb

